# Generated by Django 5.1.7 on 2025-03-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
