# Generated by Django 5.1.7 on 2025-03-27 15:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('is_working_day', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='employmentdetails',
            name='shift_end_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='position',
            name='unique_position_per_organization',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='employmentdetails',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employmentdetails',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddConstraint(
            model_name='employmentdetails',
            constraint=models.CheckConstraint(condition=models.Q(('shift_end__gt', models.F('shift_start')), ('shift_start__isnull', True), ('shift_end__isnull', True), _connector='OR'), name='shift_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('organization', 'title', 'department'), name='unique_position_per_organization'),
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='human_resources.employee'),
        ),
        migrations.AddIndex(
            model_name='employeeschedule',
            index=models.Index(fields=['employee'], name='human_resou_employe_fc9f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeschedule',
            index=models.Index(fields=['day_of_week'], name='human_resou_day_of__e8ffbd_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeschedule',
            index=models.Index(fields=['is_working_day'], name='human_resou_is_work_1edad1_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeschedule',
            constraint=models.UniqueConstraint(fields=('employee', 'day_of_week'), name='unique_schedule_per_day'),
        ),
        migrations.AddConstraint(
            model_name='employeeschedule',
            constraint=models.CheckConstraint(condition=models.Q(('shift_end__gt', models.F('shift_start'))), name='schedule_end_after_start'),
        ),
    ]
