# Generated by Django 5.1.7 on 2025-03-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_employeeschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
