# Generated by Django 5.1.7 on 2025-04-01 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0005_alter_attendance_time_in'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_period_minutes', models.PositiveIntegerField(default=15, help_text='Number of minutes allowed after shift start time before marking attendance as late')),
                ('early_check_in_minutes', models.PositiveIntegerField(default=45, help_text='Maximum number of minutes before shift start time when employees can check in')),
                ('allow_overtime', models.BooleanField(default=True, help_text='Whether to allow overtime hours')),
                ('max_overtime_hours', models.PositiveIntegerField(default=4, help_text='Maximum overtime hours allowed per day')),
                ('default_annual_leave_days', models.PositiveIntegerField(default=20, help_text='Default number of annual leave days for new employees')),
                ('default_sick_leave_days', models.PositiveIntegerField(default=10, help_text='Default number of sick leave days for new employees')),
                ('allow_leave_carryover', models.BooleanField(default=True, help_text='Whether to allow leave days to be carried over to next year')),
                ('max_leave_carryover_days', models.PositiveIntegerField(default=5, help_text='Maximum number of leave days that can be carried over')),
                ('standard_working_hours', models.PositiveIntegerField(default=8, help_text='Standard working hours per day')),
                ('standard_working_days', models.PositiveIntegerField(default=5, help_text='Standard working days per week')),
                ('lunch_break_minutes', models.PositiveIntegerField(default=60, help_text='Standard lunch break duration in minutes')),
                ('tea_break_minutes', models.PositiveIntegerField(default=15, help_text='Standard tea break duration in minutes')),
                ('notify_late_attendance', models.BooleanField(default=True, help_text='Whether to notify managers of late attendance')),
                ('notify_early_checkout', models.BooleanField(default=True, help_text='Whether to notify managers of early checkouts')),
                ('notify_leave_requests', models.BooleanField(default=True, help_text='Whether to notify managers of leave requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_preferences', to='organization.organization')),
            ],
            options={
                'verbose_name': 'HR Preferences',
                'verbose_name_plural': 'HR Preferences',
                'indexes': [models.Index(fields=['organization'], name='human_resou_organiz_7e7f20_idx')],
            },
        ),
    ]
