# Generated by Django 5.2 on 2025-04-23 07:29

import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='currency',
            field=models.CharField(choices=[('USD', 'American Dollar'), ('EUR', 'Europen Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('HTG', 'Haitian Gourde'), ('AUD', 'Australian Dollar'), ('DOM', 'Dominican Peso')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos', validators=[organization.models.validate_image_file]),
        ),
    ]
