# Generated by Django 5.2 on 2025-04-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_preference_currency_alter_organization_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='currency',
        ),
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(choices=[('USD', 'American Dollar'), ('EUR', 'Europen Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('HTG', 'Haitian Gourde'), ('AUD', 'Australian Dollar'), ('DOM', 'Dominican Peso')], default='USD', max_length=3),
        ),
    ]
