# Generated by Django 5.2 on 2025-04-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_preference_currency_organization_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='logo_url',
            new_name='logo',
        ),
    ]
