# Generated by Django 5.1.7 on 2025-03-26 23:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import timezone_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ht', 'Kreyol')], max_length=2, unique=True)),
                ('name', models.CharField(editable=False, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'indexes': [models.Index(fields=['name'], name='core_langua_name_4f83d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VIEW_ORGANIZATION', 'View Organization Information'), ('EDIT_ORGANIZATION', 'Edit Organization Information'), ('DELETE_ORGANIZATION', 'Delete Organization Information'), ('TRANSFER_OWNERSHIP', 'Transfer Ownership'), ('VIEW_ORGANIZATION_ADDRESSES', 'View Organization Addresses'), ('CREATE_ORGANIZATION_ADDRESSES', 'Create Organization Address'), ('EDIT_ORGANIZATION_ADDRESSES', 'Edit Organization Addresses'), ('DELETE_ORGANIZATION_ADDRESSES', 'Delete Organization Addresses'), ('VIEW_ORGANIZATION_INVOICE_CONFIG', 'View Organization Invoice Config'), ('CREATE_ORGANIZATION_INVOICE_CONFIG', 'Create Organization Invoice Config'), ('EDIT_ORGANIZATION_INVOICE_CONFIG', 'Edit Organization Invoice Config'), ('DELETE_ORGANIZATION_INVOICE_CONFIG', 'Delete Organization Invoice Config'), ('VIEW_ORGANIZATION_INVOICE_ITEM', 'View Organization Invoice Items'), ('CREATE_ORGANIZATION_INVOICE_ITEM', 'Create Organization Invoice Items'), ('EDIT_ORGANIZATION_INVOICE_ITEM', 'Edit Organization Invoice Items'), ('DELETE_ORGANIZATION_INVOICE_ITEM', 'Delete Organization Invoice Items'), ('VIEW_ORGANIZATION_PAYMENT_METHOD', 'View Organization Payment Methods'), ('CREATE_ORGANIZATION_PAYMENT_METHOD', 'Create Organization Payment Methods'), ('EDIT_ORGANIZATION_PAYMENT_METHOD', 'Edit Organization Payment Methods'), ('DELETE_ORGANIZATION_PAYMENT_METHOD', 'Delete Organization Payment Methods'), ('VIEW_ORGANIZATION_NOTIFICATION_PREFERENCES', 'View Organization Notification Preferences'), ('CREATE_ORGANIZATION_NOTIFICATION_PREFERENCES', 'Create Organization Notification Preferences'), ('EDIT_ORGANIZATION_NOTIFICATION_PREFERENCES', 'Edit Organization Notification Preferences'), ('DELETE_ORGANIZATION_NOTIFICATION_PREFERENCES', 'Delete Organization Notification Preferences'), ('VIEW_ORGANIZATION_MEMBER', 'View Organization Members'), ('EDIT_ORGANIZATION_MEMBER', 'Edit Organization Members'), ('DELETE_ORGANIZATION_MEMBER', 'Delete Organization Members'), ('CREATE_MEMBER_INVITATION', 'Create Member Invitation'), ('DELETE_MEMBER_INVITATION', 'Delete Member Invitation'), ('EDIT_MEMBER_INVITATION', 'EDIT Member Invitation'), ('VIEW_ORGANIZATION_ROLE', 'View Organization Roles'), ('CREATE_ORGANIZATION_ROLE', 'Create Organization Roles'), ('EDIT_ORGANIZATION_ROLE', 'Edit Organization Roles'), ('DELETE_ORGANIZATION_ROLE', 'Delete Organization Roles'), ('VIEW_ORGANIZATION_GROUP', 'View Organization Groups'), ('CREATE_ORGANIZATION_GROUP', 'Create Organization Groups'), ('EDIT_ORGANIZATION_GROUP', 'Edit Organization Groups'), ('DELETE_ORGANIZATION_GROUP', 'Delete Organization Groups'), ('VIEW_ORGANIZATION_DEPARTMENT', 'View Organization Departments'), ('CREATE_ORGANIZATION_DEPARTMENT', 'Create Organization Departments'), ('EDIT_ORGANIZATION_DEPARTMENT', 'Edit Organization Departments'), ('DELETE_ORGANIZATION_DEPARTMENT', 'Delete Organization Departments'), ('VIEW_ORGANIZATION_POSITION', 'View Organization Positions'), ('CREATE_ORGANIZATION_POSITION', 'Create Organization Positions'), ('EDIT_ORGANIZATION_POSITION', 'Edit Organization Positions'), ('DELETE_ORGANIZATION_POSITION', 'Delete Organization Positions'), ('VIEW_ORGANIZATION_EMPLOYEE', 'View Organization Employees'), ('CREATE_ORGANIZATION_EMPLOYEE', 'Create Organization Employees'), ('EDIT_ORGANIZATION_EMPLOYEE', 'Edit Organization Employees'), ('DELETE_ORGANIZATION_EMPLOYEE', 'Delete Organization Employees')], max_length=100, unique=True)),
                ('category', models.CharField(blank=True, choices=[('ORGANIZATION', 'Organization'), ('STORE', 'Store'), ('INVOICE', 'Invoice'), ('MEMBER', 'Member'), ('PAYMENT', 'Payment'), ('ADDRESS', 'Address'), ('ROLE', 'Role'), ('GROUP', 'Group'), ('DEPARTMENT', 'Department'), ('POSITION', 'Position'), ('EMPLOYEE', 'Employee')], editable=False, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Permissions',
                'indexes': [models.Index(fields=['name'], name='core_permis_name_3755ec_idx'), models.Index(fields=['category'], name='core_permis_categor_02cd82_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_permission_name')],
            },
        ),
    ]
