# Generated by Django 5.1.7 on 2025-04-04 19:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name', 'company_name']},
        ),
        migrations.AddField(
            model_name='payment',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount that is pending validation', max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='finance.address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('PARTIALLY_PAID', 'Partially Paid')], default='DRAFT', max_length=20),
        ),
    ]
