# Generated by Django 5.1.7 on 2025-04-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_client_options_payment_pending_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pending_amount',
        ),
    ]
