# Generated by Django 5.2 on 2025-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_client_address_address_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
