# Generated by Django 5.2 on 2025-04-05 21:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_client_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='allow_partial_payments',
            field=models.BooleanField(default=False, help_text='Whether partial payments are allowed'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_date',
            field=models.DateField(blank=True, help_text='Date when the last reminder was sent', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fee_applied',
            field=models.BooleanField(default=False, help_text='Whether late fee has been applied'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late fee percentage to apply on overdue invoices', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='minimum_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum payment amount if partial payments are allowed', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_reminders_sent',
            field=models.PositiveIntegerField(default=0, help_text='Number of payment reminders sent'),
        ),
    ]
