# Generated by Django 5.2 on 2025-04-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_invoice_allow_partial_payments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='allow_partial_payments',
            field=models.BooleanField(default=False, editable=False, help_text='Whether partial payments are allowed'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_reminder_date',
            field=models.DateField(blank=True, editable=False, help_text='Date when the last reminder was sent', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='late_fee_applied',
            field=models.BooleanField(default=False, editable=False, help_text='Whether late fee has been applied'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_reminders_sent',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of payment reminders sent'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card'), ('PAYPAL', 'PayPal'), ('MON_CASH', 'Mon Cash'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
