# Generated by Django 5.2 on 2025-04-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_client_options_remove_client_company_name_and_more'),
        ('organization', '0003_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BANNED', 'Banned')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='finance_cli_name_9aa189_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='finance_cli_email_50f0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone'], name='finance_cli_phone_8e87b0_idx'),
        ),
    ]
