# Generated by Django 5.2 on 2025-04-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_client_name_alter_client_phone_and_more'),
        ('organization', '0003_invitation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='finance_cli_status_173afb_idx'),
        ),
    ]
