# Generated by Django 5.2 on 2025-04-13 03:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_client_finance_cli_status_173afb_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Late fee amount', max_digits=10),
        ),
    ]
