# Generated by Django 5.2 on 2025-04-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_invoice_late_fee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('PARTIALLY_PAID', 'Partially Paid')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card'), ('WIRE_TRANSFER', 'Wire Transfer'), ('CHECK', 'Check'), ('PAYPAL', 'PayPal'), ('MON_CASH', 'MonCash')], max_length=20),
        ),
    ]
