# Generated by Django 5.2 on 2025-04-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_payment_notes_alter_payment_payment_method_and_more'),
        ('organization', '0004_preference_currency_alter_organization_logo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['issue_date']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='allow_partial_payments',
            field=models.BooleanField(default=False, help_text='Whether partial payments are allowed'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='finance_inv_issue_d_3b7e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='finance_inv_due_dat_b93853_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='finance_inv_status_d9b47e_idx'),
        ),
    ]
