# Generated by Django 5.2 on 2025-04-25 18:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_invoice_options_and_more'),
        ('organization', '0006_rename_logo_url_organization_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(choices=[('PAYROLL', 'Payroll & Benefits'), ('RENT', 'Rent & Utilities'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('EQUIPMENT', 'Equipment & Machinery'), ('SOFTWARE', 'Software & Technology'), ('MARKETING', 'Marketing & Advertising'), ('TRAVEL', 'Travel & Entertainment'), ('PROFESSIONAL_SERVICES', 'Professional Services'), ('INSURANCE_BUSINESS', 'Business Insurance'), ('TAXES', 'Taxes & Licenses'), ('MAINTENANCE', 'Maintenance & Repairs'), ('TRAINING', 'Training & Development'), ('SUBSCRIPTIONS', 'Subscriptions & Memberships'), ('INVENTORY', 'Inventory & Supplies'), ('SHIPPING', 'Shipping & Logistics'), ('LEGAL', 'Legal & Professional Fees'), ('BANK_FEES', 'Bank & Financial Fees'), ('RESEARCH', 'Research & Development'), ('HOUSING', 'Housing & Rent'), ('TRANSPORTATION', 'Transportation'), ('FOOD', 'Food & Dining'), ('UTILITIES', 'Personal Utilities'), ('ENTERTAINMENT', 'Entertainment'), ('INSURANCE_PERSONAL', 'Personal Insurance'), ('HEALTHCARE', 'Healthcare & Medical'), ('EDUCATION', 'Education'), ('GIFTS', 'Gifts & Donations'), ('DEBT', 'Debt Payments'), ('PERSONAL', 'Personal Care'), ('INVESTMENTS', 'Investments'), ('CHILDCARE', 'Childcare'), ('PETS', 'Pet Expenses'), ('CLOTHING', 'Clothing'), ('OTHER', 'Other Expenses')], max_length=30)),
                ('expense_type', models.CharField(choices=[('RECURRING', 'Recurring'), ('ONE_TIME', 'One Time')], default='ONE_TIME', max_length=20)),
                ('frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('BIANNUAL', 'Bi-Annual'), ('YEARLY', 'Yearly')], max_length=20, null=True)),
                ('date', models.DateField(help_text='Start date for recurring expenses, or expense date for one-time expenses')),
                ('billing_day', models.PositiveIntegerField(blank=True, help_text='Day of the period when billing occurs (e.g., day of month for monthly billing)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('recurring_status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('PAUSED', 'Paused'), ('ENDED', 'Ended')], help_text='Status of recurring expense subscription', max_length=20, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for recurring expenses', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='organization.organization')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['category'], name='finance_exp_categor_54fa26_idx'), models.Index(fields=['date'], name='finance_exp_date_677539_idx'), models.Index(fields=['expense_type'], name='finance_exp_expense_f68925_idx'), models.Index(fields=['recurring_status'], name='finance_exp_recurri_14f6a1_idx')],
            },
        ),
    ]
