# Generated by Django 5.2 on 2025-04-26 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='finance.client'),
        ),
    ]
