# Generated by Django 5.2 on 2025-04-29 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_alter_address_client'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='finance_exp_recurri_14f6a1_idx',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='recurring_status',
        ),
        migrations.AlterField(
            model_name='expense',
            name='billing_day',
            field=models.PositiveIntegerField(blank=True, help_text='Day of the period when billing occurs (e.g., 15 for monthly expenses that bill on the 15th)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('PAYROLL', 'Payroll & Benefits'), ('RENT', 'Rent & Utilities'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('EQUIPMENT', 'Equipment & Machinery'), ('SOFTWARE', 'Software & Technology'), ('MARKETING', 'Marketing & Advertising'), ('TRAVEL', 'Travel & Entertainment'), ('PROFESSIONAL_SERVICES', 'Professional Services'), ('INSURANCE_BUSINESS', 'Business Insurance'), ('TAXES', 'Taxes & Licenses'), ('MAINTENANCE', 'Maintenance & Repairs'), ('TRAINING', 'Training & Development'), ('SUBSCRIPTIONS', 'Subscriptions & Memberships'), ('INVENTORY', 'Inventory & Supplies'), ('SHIPPING', 'Shipping & Logistics'), ('LEGAL', 'Legal & Professional Fees'), ('BANK_FEES', 'Bank & Financial Fees'), ('RESEARCH', 'Research & Development'), ('OTHER', 'Other Expenses')], max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50),
        ),
    ]
