# Generated by Django 5.2 on 2025-04-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_remove_expense_finance_exp_recurri_14f6a1_idx_and_more'),
        ('organization', '0006_rename_logo_url_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('FIXED', 'Fixed Date'), ('RELATIVE', 'Relative to Start')], help_text='Whether billing is on a fixed date or relative to start date', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['billing_type'], name='finance_exp_billing_0e7a10_idx'),
        ),
    ]
