# Generated by Django 5.2 on 2025-04-29 18:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_expense_billing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='prepaid_periods',
            field=models.PositiveIntegerField(default=0, help_text='Number of periods that have been prepaid (e.g., 5 for 5 months of prepaid gym membership)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount per period (e.g., monthly amount for monthly expenses)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
