# Generated by Django 5.2 on 2025-05-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_expense_prepaid_periods_alter_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
